import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { ReactQueryProvider } from "utils/ReactQueryProvider";
import { Provider } from "react-redux";
import { store } from "../../redux/store";
import { ReduxProvider } from "utils/ReduxProvider";

export const metadata: Metadata = {
  title: "USA-WASH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-full bg-background ">
        <ReduxProvider>
          <ReactQueryProvider>
            <div>{children}</div>
          </ReactQueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
