import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { ReactQueryProvider } from "utils/ReactQueryProvider";
import { ReduxProvider } from "utils/ReduxProvider";
import { ProtectedRoutes } from "utils/ProtectedRoutes";
import { ReactToastifyProvider } from "utils/ReactToastifyProvider";

export const metadata: Metadata = {
  title: "USA-WASH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-full bg-background ">
        <ReduxProvider>
          <ReactQueryProvider>
            <ProtectedRoutes>
              <ReactToastifyProvider>
                <div>{children}</div>
              </ReactToastifyProvider>
            </ProtectedRoutes>
          </ReactQueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
